name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls the code from GitHub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables advanced Docker builds

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Use the root directory for the build
          file: ./Dockerfile  # Path to Dockerfile
          push: true  # Push image to Docker Hub
          tags: your-dockerhub-username/fastapi-app:latest
